services:
  - type: web
    name: rtc-app
    env: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: NODE_ENV
        value: production
      - key: MYSQL_HOST
        sync: false
      - key: MYSQL_PORT
        sync: false
      - key: MYSQL_USER
        sync: false
      - key: MYSQL_PASSWORD
        sync: false
      - key: MYSQL_DATABASE
        sync: false
      - key: JWT_SEC
        sync: false
      - key: REFRESH_TOKEN
        sync: false
      - key: REDIS_URL
        sync: false
      - key: PORT
        value: 8080
    healthCheckPath: /health
    autoDeploy: true
